# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
pod 'Firebase/Core'
pod 'Firebase/Database'

target 'matchLive' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for matchLive

  target 'matchLive-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'matchLiveTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'matchLive-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for matchLive-tvOS


end
